version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for frontend"
      - cd frontend
      - npm install

  pre_build:
    commands:
      - echo "Node version:"
      - node --version

  build:
    commands:
      - echo "Running React build"
      - npm run build
      - echo "Copy buildspec-frontend-test.yml into build folder for Integration Test"
      - cp ../buildspec-frontend-test.yml build/buildspec-frontend-test.yml
      - cp ../buildspec-frontend-invalidate.yml build/buildspec-frontend-invalidate.yml

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'
