version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies for frontend"
      - cd frontend
      - npm install
  pre_build:
    commands:
      - echo "Node version:"
      - node --version
  build:
    commands:
      - echo "Running React build"
      - cd frontend
      - npm run build
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'
