version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "=== BACKEND UNIT TEST / INSTALL ==="
      - echo "PWD:" && pwd
      - echo "Repo root:" && ls
      - echo "cd backend"
      - cd backend
      - echo "PWD after cd backend:" && pwd
      - echo "Files in backend:" && ls
      - pip install -r requirements.txt
      - pip install pytest || echo "pytest already installed or not needed"

  build:
    commands:
      - echo "=== BACKEND UNIT TEST / BUILD ==="
      - |
        if [ -d "tests" ]; then
          echo "tests/ found, running pytest..."
          pytest
        else
          echo "No tests directory, skipping unit tests."
        fi

artifacts:
  files:
    - '**/*'
  discard-paths: yes
