name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/build_docker.yaml"

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./backend/ -t tenebris2/qairline-repo:backend
      - name: push image to dockerhub
        run: |
          docker login -u tenebris2 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push tenebris2/qairline-repo:backend
